name: transliteration
description: Transliteration package which transliterates "English" to more than
  20 languagues.
version: 0.0.4
homepage: https://github.com/jaydangar/transliteration

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
